name: Test

on:
  pull_request:
  push:
    branches: 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Package Managers
        run: corepack enable

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Check
        run: npm run check

      - name: Build
        run: npm run build
